site_name: GSoC-RedHenLab-MTVSS-2022
site_url: https://GSoC-RedHenLab-MTVSS-2022.com/
nav:
  - Home: index.md
  - mtvss: mtvss/main.md
  - inaSpeechSegmenter: iss/main.md
theme: readthedocs
plugins:
  - mkdocstrings
watch:
  - .  # reload docs for any file changes