name: Docker

on:
  push:
  pull_request:

jobs:
  build_publish_containers:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

  with:
    submodules: recursive

      - name: Build/push
        uses: whoan/docker-build-with-cache-action@v5
        with:
          dockerfile: docker/
          registry: ghcr.io
          image_name: ${{ github.actor }}/MultimodalTVShowSeg-2022
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}